### ISSUE TITLE
SRAM saving not working for ED64P

### ISSUE THREAD

**Issue by chmcarro** [hcs64/neon64v2#11]
Unable to utilize game saves in SRAM on the ED64P stock OS or Alt64 OS.

**Comment by chmcarro** [comment]
Update - this is partially working, but not fully fleshed out.

With the stock ED64P firmware, you must first use the R trigger to 'Force SRAM', then in the NES ROM, use L+R and select save. Upon replays, remember to 'Force SRAM' and save.

For Alt64, there is no config option for .nes files to set the save type. It appears that between power cycles, you can use saves, but the saves are gone with powering off the console.

**Comment by hcs64** [comment]
To the best of my knowledge there's no way for Neon64 to report that it needs SRAM, this is something the firmware needs to figure out for itself with a database of save types or similar. I'm happy to reopen this is there's something that can change on my end, but for now I suggest asking the developer to add whatever version of Neon64 you want to run to their list, which may need to be updated with each new version. Unfortunately N64 ROMs don't have a header for info about cartridge hardware, so external databases are needed.

**Comment by ariahiro64** [comment]
Hold my beer

**Comment by ariahiro64** [comment]
i made a new build of altra64 with saves enabled.
[ED64P.zip](https://github.com/hcs64/neon64v2/files/6437936/ED64P.zip)
this is save ram 128

let me know if this works

**Comment by ariahiro64** [comment]
as a temporary solution a buddy witten a program that pads roms in D
[nes_padder.zip](https://github.com/hcs64/neon64v2/files/6476562/nes_padder.zip)
