### ISSUE TITLE
Mega Man 3 Stage Select Regression

### ISSUE THREAD

**Issue by ghost** [hcs64/neon64v2#12]
Stage/boss select screen exhibits a thin horizontal line of garbage pixels along one of the seams where the screen "slides" into view. Located right above the Shadow Man square. Issue is not present in Visor's 0.3c build based on v1.2.

**Comment by hcs64** [comment]
This is a bug in the game, see e.g. [this hardware recording from a speedrun](https://youtu.be/oDj1yVPPqcM?t=4). Neon64 1.2 was not accurate enough for mid-scanline stuff so it doesn't show up.

I was going to suggest trying a hack like [Mega Man 3 Improvement](http://www.romhacking.net/hacks/992/) which fixes this, but it looks like the current timing is sufficiently far off that it has an even worse issue, the whole bottom of the screen bounces. This is probably related to the [EOL early hack](https://github.com/hcs64/neon64v2/blob/f55ee3bd6a082016b73a8d008600d087d3881e8b/src/ppu_task.asm#L586-L592) that I'd like to get rid of.

**Comment by hcs64** [comment]
Thanks for trying it out, and welcome to GitHub!
