### ISSUE TITLE
The syntax of the command is incorrect error neon64v2

### ISSUE THREAD

**Issue by hubert838** [hcs64/neon64v2#23]
Hello!
i type this copy /b neon64bu.rom + Sonic The Hedgehog.nes game.n64 in cmd and got this error message "The syntax of the command is incorrect." is so annoying!
![image](https://user-images.githubusercontent.com/69467708/210083996-bcc6114d-cd9c-4717-a6eb-cf64faf6f6cc.png)

**Comment by Eloeri** [comment]
You need quotations around the rom name `copy /b neon64bu.rom + "Sonic The Hedgehog.nes" game.n64`
