### ISSUE TITLE
Bomberman 2

### ISSUE THREAD

**Issue by Valkristh** [hcs64/neon64v2#3]
hello i have been testing games (in my ed64+, neon64v2 beta 3) and found one bug in Bomberman 2 (usa), it has a strange repetitive sound when starting (like when bombs explode) and when playing, the sound of the explosion repeats itself.
keep up the good work! it's an amazing emulator

**Comment by hcs64** [comment]
Confirmed, I'll look into whether I'm messing up DMC looping somehow.

**Comment by hcs64** [comment]
Should be fixed on master, but I noticed that there's some kind of hang if you let the title screen idle and fade out to show the demo. It seems to get in game ok, at least.
