### ISSUE TITLE
VS Ice Climber MMC1 hack bad opcode

### ISSUE THREAD

**Issue by hcs64** [hcs64/neon64v2#9]
OK, interesting. I have the latest patch, but VS Ice climbers throws a different error, not the unsupported mapper error.

Bad opcode: $4b at PC=$c0a2, P=$27, A=$00, X=$00, Y=$00, S=$fd, cycle=216624

_Originally posted by @chmcarro in https://github.com/hcs64/neon64v2/issues/7#issuecomment-771905146_

**Comment by hcs64** [comment]
This might be an intentional use of the unofficial $4b opcode, or it could be a crash for some other reason (bug in Neon64 or the hack).

**Comment by hcs64** [comment]
Or as @oRBIT2002 pointed out in https://github.com/hcs64/neon64v2/issues/7#issuecomment-771945330, it could be patched on the wrong ROM. @chmcarro, could you upload the patched ROM somewhere, or provide a hash (e.g. CRC32) from before patching so I can try to reproduce it?

**Comment by chmcarro** [comment]
Name: VS. Ice Climber (VS) NES Patched v2.0b [FIX] Morgan Johansson.nes
Size: 81936 bytes (80 KiB)
CRC32: D732018E


Runs great in Mesen v0.9.9

**Comment by chmcarro** [comment]
Good news - this issue can be closed.

This is an old patch from 2013. The later patch from 2017 works fine on Neon64.
v2.1
CRC32: C6CCF3CC

**Comment by hcs64** [comment]
Thanks for following up, glad the new one works!
